version: '2'

services:

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_SCANNER_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000"
    ports:
      - "19000:9000"
      - "18000:8000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - "./sonarqube_ext_plugins:/opt/sonarqube/extensions/plugins"
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

  microcks-mongo:
    image: mongo:4.4.29
    container_name: microcks-mongo
    volumes:
      - "./db-microcks/microcks-data:/data/db"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: microcks-sso
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:18080"
      KC_HOSTNAME_URL: "http://localhost:18080"
    volumes:
      - "./keycloak-realm/microcks-realm.json:/opt/keycloak/data/import/microcks-realm.json"
    command: [ "start-dev", "--import-realm" ]

  postman:
    image: quay.io/microcks/microcks-postman-runtime:0.6.0
    container_name: microcks-postman-runtime

  microcks:
    depends_on:
      - microcks-mongo
      - keycloak
      - postman
    image: quay.io/microcks/microcks:1.10.1-fix-1
    container_name: microcks
    ports:
      - "38080:8080"
      - "39090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://microcks-mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_PUBLIC_URL=http://localhost:18080
      - JAVA_OPTIONS=-Dspring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:18080/realms/microcks -Dspring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/microcks/protocol/openid-connect/certs
      #- MAX_UPLOAD_FILE_SIZE=3MB

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data: